# name: Run tests
#
# on:
#   push:
#     branches:
#     - main
#     - release/*
#   pull_request:
#     branches:
#     - main
#
# jobs:
#   test:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       fail-fast: false
#       matrix:
#         julia-version:
#           - '1.6'
#           - 'nightly'
#         os:
#           - ubuntu-latest
#           - macOS-latest
#         julia-arch:
#           - x64
#
#     steps:
#       - uses: actions/checkout@v2
#       - uses: julia-actions/setup-julia@latest
#         with:
#           version: ${{ matrix.julia-version }}
#           arch: ${{ matrix.julia-arch }}
#
#       - uses: julia-actions/julia-buildpkg@latest
#       - uses: julia-actions/julia-runtest@latest
#
